AllCops:
  TargetRubyVersion: 2.5.0
  Exclude:
    - vendor/**/*

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Max: 50

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: percent_r
  Include:
    - Guardfile
